apiVersion: v1
kind: Service
metadata:
  name: pr-agent-service
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: pr-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pr-agent
  name: pr-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pr-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pr-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - image: martinyunify/pr-agent:github_app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: pr-agent
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/pr_agent/settings_prod/.secrets.toml
          name: secrets-volume
          subPath: .secrets.toml
        - mountPath: /app/pr_agent/settings_prod/allowed_repos.toml
          name: pr-agent-config-volume
          subPath: allowed_repos.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets-volume
        secret:
          defaultMode: 420
          secretName: kaito-pr-agent-secrets
      - configMap:
          defaultMode: 420
          name: pr-agent-config
        name: pr-agent-config-volume
