apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-qwen-2-5-coder-32b-instruct-with-adapter
inference:
  preset:
    accessMode: public
    name: qwen2.5-coder-32b-instruct
  adapters:
    - source:
        name: "qwen-32b-adapter"
        image: "kaitosample.azurecr.io/go-operator-reviewer-data-adapter:0.0.1"
        imagePullSecrets:
          - registry-push-secret
resource:
  instanceType: Standard_NC24ads_A100_v4
  labelSelector:
    matchLabels:
      apps: qwen-with-adapter
