# This rule is not used by the project kaito-sample-repo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kaito.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaito-sample-repo
    app.kubernetes.io/managed-by: kustomize
  name: batchjob-viewer-role
rules:
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs/status
  verbs:
  - get
