# This rule is not used by the project kaito-sample-repo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kaito.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaito-sample-repo
    app.kubernetes.io/managed-by: kustomize
  name: batchjob-admin-role
rules:
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs
  verbs:
  - '*'
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs/status
  verbs:
  - get
