---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kaito.dev
  resources:
  - batchjobs/status
  verbs:
  - get
  - patch
  - update
