apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-tuning-qwen
resource:
  instanceType: "Standard_NC24ads_A100_v4"
  labelSelector:
    matchLabels:
      app: tuning-qwen
tuning:
  preset:
    name: qwen2.5-coder-32b-instruct
  method: qlora
  input:
    image: "kaitosample.azurecr.io/go-operator-reviewer-data:0.0.1" # dataset image
    imagePullSecrets:
      - registry-push-secret
  output:
    image: "kaitosample.azurecr.io/go-operator-reviewer-data-adapter:0.0.1" # adapter image
    imagePushSecret: registry-push-secret
